# Dep image
#   docker build --build-arg BASE_IMAGE=ubuntu:noble -f docker/Dockerfile.deps -t xxx .
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY --chmod=755 install_deps.sh /tmp/install_deps.sh
COPY builddep/ /tmp/builddep/
# install_deps.sh handles EOL archive switching (buster unconditional, bullseye probed) and APT_MIRROR
RUN cd /tmp && ./install_deps.sh && rm -rf /tmp/install_deps.sh /tmp/builddep
